### PR TITLE
profcheck: use dedicated check for AttributeTable

### LINKED ISSUE #1360: Bug: profiles from ebpf-profiler:0.150.1 are failing the dict check for attribute_table
Profiles ~~generated with the ebpf-profiler~~ emitted from the OTEL pipeline have an invalid value at the 0-th position in the attribute table map. The conformance check tool is flagging the issue correctly.

> Edit: seems to be due to grpc (un-)marshalling.

Error: 
> setup_3_grpc_file/out/profiles_1776370937817061840.pb: conformance checks failed: dictionary: attribute_table: must have zero value &v1development.KeyValueAndUnit

When debugging I saw the following:

Expected `new(T)`: 
```
v1development.KeyValueAndUnit {state: impl.MessageState {NoUnkeyedLiterals: pragma.NoUnkeyedLiterals {}, DoNotCompare: pragma.DoNotCompare [], DoNotCopy: pragma.DoNotCopy [], atomicMessageInfo: *impl.MessageInfo nil}, sizeCache: 0, unknownFields: []uint8 len: 0, cap: 0, nil, KeyStrindex: 0, 
	Value: *v1.AnyValue nil, UnitStrindex: 0}
```

Actual `table[0]`:
```
*v1development.KeyValueAndUnit {state: impl.MessageState {NoUnkeyedLiterals: pragma.NoUnkeyedLiterals {}, DoNotCompare: pragma.DoNotCompare [], DoNotCopy: pragma.DoNotCopy [], atomicMessageInfo: *impl.MessageInfo nil}, sizeCache: 0, unknownFields: []uint8 len: 0, cap: 0, nil, KeyStrindex: 0, 
	Value: *v1.AnyValue {state: (*"impl.MessageState")(0x3d1efaa5040), sizeCache: 0, unknownFields: []uint8 len: 0, cap: 0, nil, Value: v1.isAnyValue_Value nil}, UnitStrindex: 0}
```
Value looks empty, but is not in fact nil.

The particular failing check: https://github.com/open-telemetry/sig-profiling/blob/main/profcheck/check.go#L376

Writing to json file nets the following:
json: `"attributeTable":[{"value":{}}`

But I also tested capturing the grpc request and unmarshalling - same json representation: 
pb -> inspect -> out.json: `"attributeTable":[{"value": {}},`

where inspect is something I quickly cobbled together to print the .pb files.

**Reproduced** here: https://github.com/bmarinov/ebpf-profiler-pipeline-dbg/tree/main/repro/setup_3_grpc_file

Sample file (otel grpc exporter -> .pb -> inspect command from the linked repo.
[profiles_1776376300858502811.pb.json](https://github.com/user-attachments/files/26827038/profiles_1776376300858502811.pb.json)

I managed to get the same error with all four scenarios. Most of this is unrelated to this particular issue, but all four setups and OTEL pipelines end up with the same invalid profiles:
- setup_1: profiler -> collector (filter) -> json file
- setup_2: profiler -> json file
- setup_3:
  - profiler -> grpc endpoint -> pb file -> conformance tool
  - profiler -> grpc endpoint -> pb file -> json (main.go -> inspect)
- setup_4: profiler -> filter -> pb file

### PR DESCRIPTION
**Pull request by florianl**
As KeyValueAndUnit uses pcommon.AnyValue as type for field Value we need to explicitly check the value of pcommon.AnyValue if it is nil rather than check if Value of KeyValueAndUnit is nil.

Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/1360 and avoid the need for work arounds in various places.

### CODE REVIEW

File: profcheck/check.go [hunk 1]
```diff
@@ -346,6 +346,25 @@ func (c ConformanceChecker) checkAttributeTable(attrTable []*profiles.KeyValueAn
 	return errs
 }
 
+// checkAttributeTableZeroVal verifies that the AttributeTable meets Profiles
+// dictionary conventions: the slice is not empty and the first entry has zero
+// key and unit indices and the value field holds nil as value.
+func checkAttributeTableZeroVal(attrTable []*profiles.KeyValueAndUnit) error {
+	if len(attrTable) == 0 {
+		return errors.New("empty table, must have at least zero value entry")
```
Comment (christos68k) [inline profcheck/check.go:354]:
```suggestion
		return errors.New("empty attribute table, must have at least zero value entry")
```

**Review by christos68k — APPROVED** [review]

**Comment by aalexand** [comment]
@florianl Curious - why is it not "pure" zero value with all fields unset? Why is the value field set?

File: profcheck/check.go (hunk 1 above)
Comment (florianl) [reply profcheck/check.go:354]: For consistency with `checkZeroVal()` I'm keeping the error message.

**Comment by florianl** [comment]
> why is it not "pure" zero value with all fields unset? Why is the value field set?

The core issue is an encoding problem. Since the `Value` field within `KeyValueAndUnit` is not a pointer receiver, it is always initialized. Therefore, to check if the value is meaningfully absent, we must inspect the inner `Value.value` field of `KeyValueAndUnit.Value` for `nil`.
Since the OTel ecosystem relies on a custom implementation for marshaling and unmarshaling protobufs, we must address this case, even though other Go protobuf implementations might handle it differently.

**Review by aalexand — APPROVED** [review]

File: profcheck/check.go (hunk 1 above)
Comment (christos68k) [reply profcheck/check.go:354]: I think in this case, we can do better as the primary utility of this logic is to point out violations. So all these empty table errors (not just attribute table) can be a lot better in mentioning the actual table that violates the spec (rather than "empty table" which leaves the user manually having to inspect data to figure out the source of the violation).

We don't have to do that in this PR, LMK what you think.
